# Generated by Django 5.2 on 2025-05-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
