# Generated by Django 5.2 on 2025-05-24 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_bio_user_city_remove_user_location_user_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
